<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/4/10 0010
 * Time: 13:26
 */
namespace app\admin\controller;

use think\Controller;

class Deal extends Controller{

    private $obj;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->obj = model('Deal');
    }

    public function index()
    {
        //数据表中数据
        $data = input('post.');
        //判断是否存在条件符合
        //分类
        $con_data = [];

        if(!empty($data['category_id']))
        {
            $con_data['category_id'] = $data['category_id'];

        }


        //城市
        if(!empty($data['city_id']))
        {
            $con_data['se_city_id'] = $data['city_id'];
        }
        //时间范围
        if(!empty($data['start_time']))
        {
            $con_data['start_time'] = [
              'gt',strtotime($data['start_time'])
            ];
        }
        if(!empty($data['end_time']))
        {
            $con_data['end_time'] = [
                'lt',strtotime($data['end_time'])
            ];
        }
        if(!empty($data['end_time']) && !empty($data['start_time']))
        {
            if($data['end_time'] <= $data['start_time'])
            {
                //大于
                $con_data['start_time'] =[
                    'gt',strotime($data['end_time'])
                ];
                //小于
                $com_data['end_time'] = [
                  'lt',strtotime($data['start_time'])
                ];
//                dump($con_data['start_time']);
            }
        }

        //名称
        if(!empty($data['name']))
        {
//            模糊查询
            $con_data['name'] = [
              'like' , '%'.$data['name'].'%'
            ];
        }

        $con_data['status'] = [
          'in' , [1]
        ];
        //查询deal信息
        $res = $this->obj->getDealsByCondition($con_data);
//        dump($res);
        //分类的信息 数据准备
        $categories = model('Category')->getAllFirstNormalCategories();
        //获取所有二级城市
//        dump($categories);
        $cities = model('City')->getAllNotProvinceCities();
//        dump($cities);
        //判断$data是否为空，以返回数据

        if(empty($data))
        {
            $data = [
                'category_id' =>0,
                'city_id' =>0,
                'start_time' =>'',
                'end_time' =>'',
                'name' => '',
            ];
        }
        return $this->fetch('',[
            'deals'=>$res,
            'cities' =>$cities,
            'categories'=> $categories,
            'data' => $data
            ]);

    }



}