<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/4/10 0010
 * Time: 13:26
 */
namespace app\admin\controller;

use think\Controller;

class Deal extends Controller
{

    private $obj;

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->obj = model('Deal');
    }

    public function index()
    {
        //数据表中数据
        $data = input('post.');
        //判断是否存在条件符合
        //分类
        $con_data = [];
        //判断$data是否为空，以返回数据

        if (empty($data)) {
            $data = [
                //分类
                'category_id' =>0,
                //城市
                'city_id' =>0,
                //开始时间
                'start_time' =>'',
                //结束时间
                'end_time' =>'',
                //商品名称
                'name' =>'',
            ];
        }

        if (!empty($data['category_id'])) {
            $con_data['category_id'] = $data['category_id'];

        }


        //城市
        if (!empty($data['city_id'])) {
            $con_data['se_city_id'] = $data['city_id'];
        }
        //时间范围
        if (!empty($data['start_time'])) {
            $con_data['start_time'] = [
                'gt', strtotime($data['start_time'])
            ];
        }
        if (!empty($data['end_time'])) {
            $con_data['end_time'] = [
                'lt', strtotime($data['end_time'])
            ];
        }
        if (!empty($data['end_time']) && !empty($data['start_time'])) {
            if ($data['end_time'] <= $data['start_time']) {
                //大于
                $con_data['start_time'] = [
                    'gt', strtotime($data['end_time'])
                ];
                //小于
                $com_data['end_time'] = [
                    'lt', strtotime($data['start_time'])
                ];
//                dump($con_data['start_time']);
            }
        }

        //名称
        if (!empty($data['name'])) {
//            模糊查询
            $con_data['name'] = [
                'like', '%' . $data['name'] . '%'
            ];
        }

        $con_data['status'] = [
            'in', [1]
        ];
        //查询deal信息
        $res = $this->obj->getDealsByCondition($con_data);
//        dump($res);
        //分类的信息 数据准备
        $categories = model('Category')->getAllFirstNormalCategories();
        //获取所有二级城市
//        dump($categories);
        $cities = model('City')->getAllNotProvinceCities();
//        dump($cities);

        return $this->fetch('', [
            'deals' => $res,
            'cities' => $cities,
            'categories' => $categories,
            'data' => $data
        ]);

    }

    //状态
    public function status()
    {
        $id = input('id', 0, 'intval');
        $status = input('status', 0, 'intval');
//        修改状态
        $res = $this->obj->save(['status' => $status], ['id' => $id]);
        if (!$res) {
            $this->error('状态更新失败');
        }
        $this->success('状态更新成功');
    }

    //商品团购商品审核
    public function audit()
    {
        //接受传过来的数据
        $data =input('post.');
//        dump($data);exit();
        $con_data =[];
        //判断$data是否为空，以返回数组
        if(empty($data))
        {
            $data = [
                //分类
              'category_id' =>0,
                //城市
              'city_id' =>0,
                //开始时间
              'start_time' =>'',
                //结束时间
              'end_time' =>'',
                //商品名称
              'name' =>'',
            ];
        }
        //判断是否存在条件
        //商品栏目
        if(!empty($data['category_id']))
        {
            $con_data['category_id'] = $data['category_id'];
        }
        //城市
        if(!empty($data['city_id']))
        {
            $con_data['se_city_id'] = $data['city_id'];
        }

        //开始时间
        if(!empty($data['start_time']))
        {
            $con_data['start_time'] =[
              'gt',strtotime($data['start_time'])
            ];
        }
        //结束时间
        if(!empty($data['end_time']))
        {
            $con_data['end_time'] = [
              'lt',strtotime($data['end_time'])
            ];
        }
        if(!empty($data['start_time']) && !empty($data['end_time']))
        {
            if(strtotime($data['start_time']) > strtotime($data['end_time']))
            {
                $con_data['start_time'] =[
                  'gt',strtotime($data['end_time'])
                ];
                $con_data['end_time'] =[
                  'lt',strtotime($data['start_time'])
                ];
            }
        }
        //名字
        if(!empty($data['name']))
        {
            $con_data['name'] =[
                'like','%'.$data['name'].'%'
            ];
        }
        $con_data['status'] = [
          'in',[0,1]
        ];
        //通过数据模型获取deal的信息
        $deals = $this->obj->getDealsByCondition($con_data);
        //获取分类信息
        $categories =model('Category')->getAllFirstNormalCategories();
        //获取二级城市信息
        $se_cities =model('City')->getAllNotProvinceCities();
        //状态
//        (查询所有状态)
//                $status = $this->obj->field('status')->select();
//                dump($status);
        //设置状态排序（1正常，0待审核，-1删除，2未通过）
        $status = [
            1,0,-1,2
        ];

        return $this->fetch('',[
            'deals' =>$deals,
            'categories' =>$categories,
            'cities' =>$se_cities,
            'data'=>$data,
            'status' =>$status
        ]);
    }

}